### ISSUE TITLE
When to disable NetworkManager?

### ISSUE THREAD

**Issue by aurrak** [hirak99/steam_deck_encryption#10]
In the `~/unlocker/runasroot.sh`, there is a step to run `sudo systemctl disable NetworkManager`. 

Can you clarify when that command should be run, and why do we want to prevent Steam from updating the Steam binary inside the container? 

Do we want Steam update to happen before or after the container is unlocked?

```
# After this is done, you can `sudo systemctl disable NetworkManager` to prevent Steam from
# updating the Steam binary in container (only required for keyboard) during boot.
# Line below starts it if it is disabled.
systemctl start NetworkManager
```

**Comment by hirak99** [comment]
I realize I just glossed over it. Here's a better explanation, please see if this help to clarify this more -

**Why**
It will prevent the dummy Steam Client on the non-encrypted partition to check for updates. I find it useful, since it is only needed to enter your passwords.

**Why not**
Disabling the net is an advanced call.

It is completely optional. If you do not mind keeping the dummy Steam Client to be up to date, you do not need to disable it at all.

**When**
Once you have encrypted your deck and have booted successfully, it is safe to disable it.

You must disable it before you run the unlock script.

**How**
Before unlocking, open the desktop mode and a terminal, and then enter the command -

```sh
sudo systemctl disable NetworkManager
```

**Comment by aurrak** [comment]
For some reason, I was under the impression that the Steam binary was in the immutable part of the system and there's only a single copy.

It's good to know that the disable step is optional. Thank you for the clear explanation! Perhaps it'd be useful to add that info to the README as well.
